import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ApolloWrapper } from "./ApolloWrapper";

import Gridbg from "./components/gridbg"
import Header from "./components/header";
import Guard from "./guards/Guard";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <ApolloWrapper>
          <Guard excludedRoutes={['/login','/signup']}>
            <Gridbg header={<Header />}> 
              {children}
            </Gridbg>
          </Guard>
        </ApolloWrapper>
      </body>
    </html>
  );
}
